### ISSUE TITLE
JOSE pre-submission inquiry: GemGIS and GemPy Models 

### ISSUE THREAD

**Issue by AlexanderJuestel** [openjournals/jose#14]
Dear members of JOSE's editorial board,

we would like to inquire if a contribution termed: "Form Maps to Models - Tutorials for structural geological modeling" would be within the scope of the JOSE Journal. 

We currently have a JOSS article in Review where we have introduced the software package GemGIS (https://github.com/openjournals/joss-reviews/issues/3709), a processing library to prepare spatial data for structural modeling built upon familiar packages like geopandas, rasterio, pyvista and last but not least the modeling software itself, GemPy (https://gmd.copernicus.org/articles/12/1/2019/). 

While the JOSS article is presenting the software itself, we have created several models guiding users/students through a traditional mapping course at university, and in addition to working on these mapping problems in the analog world, we would like to present the solutions and provide the motivation for students/encourage students to use open-source tools to create structural geological models to verify their analog results and to get acquainted with the Python Ecosystem. The tutorials are structured in a way that the degree of difficulty increases for each model and the models become more complex. 

Thank you very much for your thoughts!

Best regards
Alex

**Comment by AlexanderJuestel** [comment]
Pinging @moorepants

**Comment by moorepants** [comment]
Learning module submissions should have enough content for a significant portion of a college level course. If your learning module is substantial and complete for use by an instructor, then please submit for pre-review.

**Comment by AlexanderJuestel** [comment]
@moorepants we have submitted a paper to JOSE and are waiting for the start of the review now :)

**Comment by moorepants** [comment]
The main editors will assign topic editors to your paper in the submission.

**Comment by AlexanderJuestel** [comment]
Thanks for the heads up

**Comment by labarba** [comment]
hi all – can this issue be closed?
