### ISSUE TITLE
query: JOSE scope

### ISSUE THREAD

**Issue by RobinHankin** [openjournals/jose#19]
Hi there, I have written a suite of software for creating high-quality mathematical tables (logs, antilogs, and various statistical functions) released on an open-source license.  We  use them for examinations (in preference to photocopying them from a book).  Would this be of interest to JOSE?

**Comment by labarba** [comment]
hi there 👋 
Apologies that your scope-query got buried. If I understand the project, you have scripts to generate LaTeX-rendered tables of mathematical functions. I'm not sure this fits the [JOSE scope](https://openjournals.readthedocs.io/en/jose/reviewer_guidelines.html#jose-aim-and-scope). As you can read there, JOSE focuses on "computationally enabled teaching and learning." You'd have to make the case how your project aligns with that.

**Comment by RobinHankin** [comment]
hello Lorena, thanks for this.  I must admit that "computationally enabled teaching and learning"  as it stands does exclude assessment.   I would say that the production of hard-copy tables for use in written examinations [rather than photocopying tables from the back of a book, as many people do] should count as computationally-created educational resources.

But quite apart from that, I would argue that hardcopy  log tables _do_ have considerable intrinsic merit as a day-to-day educational resource:

* Extracting information from tables is a non-trivial yet useful (and teachable!) skill
* A hardcopy table shows the overall structure of functions such as log and sin in a very different way from a graph: such insight is only obtainable from tabular forms, and hardcopy emphasises such interpretations.  The top few rows of a log table, for example, are a striking illustration of the problematic behaviour of $\log_{10}(x)$ for small values of $x$
* Log and trig tables have a rich and interesting history, surely a worthy "interest" component of a general mathematics education 
* The very existence of a log table explicitly highlights to students that the logarithm function is difficult to evaluate: sufficiently difficult, in fact, to make it worthwhile for someone, somewhere, to produce a table.  Perhaps some students will value their electronic calculators more highly as a result
* By using hardcopy tables, students can gain a deeper understanding of the concepts underlying logarithms. This is because they are required to think through the relationship between the logarithmic values and the numbers they represent, rather than simply inputting values into a calculator
* Hardcopy tables promote approximation skills by only having four significant figures available: incidentally, this conveys the ultra-important yet often-ignored fact that "only" four sig figs is plenty accurate enough for many purposes; observing exactly _how_ working to only four sig figs lets one down is surely of high educational value
*  Restricting to four significant figures also helps students understand the limitations of measurement.  In many fields, it is not possible to measure values with absolute precision. Using a table of logarithms with four significant figures can help students understand that measurements and calculations always involve some degree of approximation, and can help them develop a better understanding of the limitations of measurement
* Using four significant figures, as per the tables, corresponds to 5cm (sic) error in 1km; surely a startling and memorable metaphor
* The "proportional parts" section of a typical table gives a very direct lesson about the difficulties and motivations for interpolation as a general mathematical operation [incidentally, about 99% of the conceptual difficulty of producing the tables is in the optimization of the PPs]
* Interpreting results accurately: after performing calculations, students must pay close attention to the units and significant figures of the results to ensure that they are accurate and meaningful. This requires attention to detail and a level of understanding that, arguably, electronic calculators suppress
* Occasionally, when I cannot sleep, I try to verify an entry in a log table using only paper and pencil.  This is a _very_ sobering exercise, one that  can only enhance respect for the diligent and dedicated workers, often overlooked, who originally made the tables.  The first "computers" were of course real people, and this is an important part of the history of mathematics

There does not seem to be any open-source version of log tables  available, surely an omission of interest to JOSE.  From a research perspective, it turns out that there are non-trivial mathematical details in the creation of such tables and these are set out in exhaustive detail in the repo.

Have I made a more convincing case?

**Comment by RobinHankin** [comment]
hello professor, can I enquire after my JOSE scope request about the
possibility of discussing the use of log tables in education please?
I made a justification for the alignment of such a work back in March.

Can you advise?


--
Robin K. S. Hankin
Associate Professor, computational statistics

**Comment by RobinHankin** [comment]
hello again, sorry to nag, and also I am not sure if I am asking in the right place (or indeed in the right way), but can you update me on my log tables suggestion for JOSE please?

**Comment by labarba** [comment]
Hi, and apologies for not replying to the previous comments. We discussed your enquiry with the members of the editorial board, and the consensus was that this work would not fit within the scope of JOSE. Thank you for your interest, but we are not able to accommodate the diversity of work that people contribute in the open. The editors limit the journal's scope with our best intentions to serve a subset of the open education community.

**Comment by RobinHankin** [comment]
oh well, I thought it would be worth a try.  Thank you!  Can you suggest
any alternative avenues for publication?
--
Robin K. S. Hankin
Associate Professor, computational statistics
