### ISSUE TITLE
enquiry about submission

### ISSUE THREAD

**Issue by thecraigoneill** [openjournals/jose#21]
Hi
I submitted a manuscript on the 8/3 (link here https://github.com/thecraigoneill/planet_LB). It is currently he 14/3 and I haven't heard if the submission process was successful. The emailed paper status link seems to go to a null page:
https://jose.theoj.org/papers/483df4a80d8cb5d9e3fd5a6d9d7fa136
And obviously it hasn't turned up in the review repo yet (https://github.com/openjournals/jose-reviews/issues). 
I understand this process can take time, but as the noreply submission email suggested triage might take 24 - 72 hours, I thought I might check if something hasn't gone wrong?
Thanks in advance,
Craig O'Neill

**Comment by labarba** [comment]
I moved it to Pre-Review. We just need time. This is an all-volunteer effort, incoming papers need a manual process, and I personally have a frightening backlog.

https://github.com/openjournals/jose-reviews/issues/201

**Comment by thecraigoneill** [comment]
Thank you, and sorry to be needy pain - I was just worried I may have stuffed up the submission and it was stalled somewhere. 
Lovely stuff. Cheers!
