### ISSUE TITLE
Error on submission: "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by rempsyc** [openjournals/jose#22]
Upon submission to JOSE, I am getting the following error:

![something went wrong](https://github.com/openjournals/jose/assets/13123390/2522c22c-0934-425c-8ed3-2cc9b2d1a30a)

I've tried on two browsers (Chrome & Edge) on Windows 10. Perhaps this is a temporary outage? Or could it be related to the fact that I am not able to specify the branch on which the paper is located?

I've tried providing the link to the branch instead (https://github.com/easystats/performance/tree/JOSE_paper), but it then won't accept the link (`Invalid Git repository address`). And providing the main branch (https://github.com/easystats/performance) leads to the error above.

**Comment by jncraton** [comment]
I am seeing the same error when attempting to submit a different paper, so my hunch is that the issue is not on your end.

**Comment by labarba** [comment]
I have reported this to @openjournals/dev via Slack, and they are looking into it

**Comment by arfon** [comment]
OK, this should be fixed now – I've just successfully pushed through a test submission. Sorry for the breakage here, it was an issue with our upstream email service.

**Comment by rempsyc** [comment]
Has anyone that has submitted since this issue has been solved have been able to see the status of their paper?

Edit: All good, I just had to connect before trying the link.

**Comment by jncraton** [comment]
@rempsyc Mine shows up on my profile. It currently says:

>  This paper is submitted but the review hasn't started.
