### ISSUE TITLE
"This jose.theoj.org page can’t be found"

### ISSUE THREAD

**Issue by rempsyc** [openjournals/jose#23]
Hi, we submitted a paper on May 16 and received the following message the same day:

```
Hello there, thanks for your submission to JOSE. 
Your paper, 'Check your outliers! An introduction to identifying statistical outliers in R with *easystats*', is currently 
awaiting triage by our managing editor. This generally takes between 24 and 72 hours and until then, your paper won't show 
up in the https://github.com/openjournals/jose-reviews repository. 
You can view the latest status of your paper here: https://jose.theoj.org/papers/42749638170253bb2854649fb52bf4ca 
Many thanks
The JOSE editorial robot.  
```

However, it has now been over 72 hours (a little over two weeks) and testing the link to the latest status of the paper provided in the email, I get the following error message: 

> This jose.theoj.org page can’t be found

@arfon could this be related to #22?

**Comment by arfon** [comment]
This isn't related to #22. That 404 is coming from you not being logged in. If you go to `jose.theoj.org` and log in, you will find that link works.

**Comment by rempsyc** [comment]
Indeed, I'm sorry for the confusion. It is because for JOSS, it seems one does not need to be connected to see the paper status so I thought it was similar here (but perhaps it is only so after the review starts).

Edit: For archives, I have confirmed that once the paper is first handled ("review pending" status), a connection is not necessary anymore for the link to work. The 404 will only happen between submission and the opening of the first issue on GitHub.
