### ISSUE TITLE
Submission enquiry

### ISSUE THREAD

**Issue by jatkinson1000** [openjournals/jose#28]
Dear JOSE Team,

Firstly, I know this is a volunteer effort and we are all very busy, especially at this time of year - I myself review for JOSS amongst other roles so know it can be a challenge.

I made a submission "Practical machine learning with PyTorch" around 2 months ago, but haven't had any acknowledgment, so just wanted to check that I hadn't missed a step anywhere in the submission process required to trigger review.

Thanks!

**Comment by jatkinson1000** [comment]
@labarba @jgorzalski would it be possible to get an update on this at all please?
I know you are all busy, especially this time of year, and that issues on this repo sometimes slip under the radar.
As I say above, everyone's efforts with this voluntary open journal are appreciated.

Also tagging @jdenholm as co-author.

**Comment by jatkinson1000** [comment]
Hi @labarba @arfon  I'm just wondering if JOSE is still functioning.
This was submitted 3 months ago now, with no acknowledgment yet, and I can see similar issues have been opened by other authors.
We are keen to publish with you, but if you are on hiatus/closed it would be appreciated if you could let us know.
Thanks.

**Comment by labarba** [comment]
Hi @jatkinson1000 — My sincere apologies, but I was completely crushed by editorial tasks for another publication for the bulk of 2023, and JOSE has been neglected for some months. _I have stepped down from that other role_, and will begin to pick up with JOSE now. Thank you for your patience.

**Comment by jatkinson1000** [comment]
Thanks for the update @labarba and I look forward to progressing with this.
I believe I am on your database as a reviewer, so am happy to assist with clearing the backlog where I can.

**Comment by jatkinson1000** [comment]
Closing this as pre-review has now begun over in https://github.com/openjournals/jose-reviews/issues/235
