### ISSUE TITLE
Appropriate place/address to check on status of paper

### ISSUE THREAD

**Issue by ethanwhite** [openjournals/jose#29]
We submitted a paper to JOSE 2 months ago and received a confirmation email. However the paper has never appeared in https://github.com/openjournals/jose-reviews/. Is there an appropriate email address or issue queue to inquire about its status?

**Comment by labarba** [comment]
moved recent submissions to pre-review — thanks for your patience — vacations and plenty of travel this summer

**Comment by ethanwhite** [comment]
Thanks!

**Comment by ethanwhite** [comment]
Also, if an extra set of hands to help with the editorial side of things would be useful at any point just let me know and I'd be happy to help out.
